name: SIC PA
favicon: null
layout_spectrum: 0.09127305005677044
typography_spectrum: 0.9027527910657227
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8022038175258785
  lightness: 0.8581024650484324
  saturation: 0.1618493665009737
  rhythmicContrast: 0.44504774385131896
purpose: []
